### ISSUE TITLE
Core dump: Maximum number of clients reachedthread '<unnamed>'

### ISSUE THREAD

**Issue by lindeer** [ippee/dart_clipboard#1]
```
$ uname -a
Linux localhost.localdomain 6.4.14-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep  2 16:36:06 UTC 2023 x86_64 GNU/Linux
```
and I used [the pre-build `libclipboard.so` ](https://github.com/ippee/libclipboard/releases/download/0.2.0/libclipboard.so)
error occured after running for a while:
```
Maximum number of clients reachedthread '<unnamed>' panicked at 'ClipboardProvider::new failed: XcbConn(Connection)', src/lib.rs:31:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
I called `Clipboard.setContents` many times:
```dart
    Clipboard.setContents(original);
    // require focus
    await source.click();
```
How to fix it?

**Comment by lindeer** [comment]
I set `RUST_BACKTRACE=1` env and output as:
```
Maximum number of clients reachedthread '<unnamed>' panicked at src/lib.rs:31:60:
ClipboardProvider::new failed: XcbConn(Connection)
ClipboardProvider::new failed: XcbConn(Connection)
stack backtrace:
   0:       0x7fb51ba3dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haee13570c31cb77b
   1:       0x7fb51d42a4 - core::fmt::write::he0b40f3f74e7e87c
   2:       0x7fb51b8618 - std::io::Write::write_fmt::hc8024efb884f388c
   3:       0x7fb51ba228 - std::sys_common::backtrace::print::hf1431a2be8ae8207
   4:       0x7fb51bb870 - std::panicking::default_hook::{{closure}}::ha26cf0d89fc27676
   5:       0x7fb51bb524 - std::panicking::default_hook::hddcfc2aac016eb46
   6:       0x7fb51bbc7c - std::panicking::rust_panic_with_hook::hbd9f5866892982cc
   7:       0x7fb51bbb2c - std::panicking::begin_panic_handler::{{closure}}::hf930a65f0587fc68
   8:       0x7fb51ba8a0 - std::sys_common::backtrace::__rust_end_short_backtrace::h8aeef1aadd5204df
   9:       0x7fb51bb8c4 - rust_begin_unwind
  10:       0x7fb5196930 - core::panicking::panic_fmt::h3c23aa0af13818a0
  11:       0x7fb5196c08 - core::result::unwrap_failed::h96aa0d56e71b0bb4
  12:       0x7fb519c440 - set_contents
  13:       0x7fb5a87a48 - <unknown>
fatal runtime error: failed to initiate panic, error 2952823088
```

**Comment by lindeer** [comment]
finally use 'xclip' command line, fix it. see the author's another repo [dart_clipborad2](https://github.com/ichi-h/dart_clipboard2/blob/master/lib/dart_clipboard2.dart)
